#!/usr/bin/env bash
# 10. FizzBuzz
i="0"
while [ $i -lt 100 ]; do
	if [ $((i % 5)) == 0 ] && [ $((i % 3)) == 0 ]; then
	echo "FizzBuzz"
elif [ $((i % 5)) == 0 ]; then
	echo "Fizz"
elif [ $((i % 3)) == 0 ]; then
	echo "Fizz"
else
	echo $i
fi
	((i+=1))
done
