#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i="0"
while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i -eq 1 ]; then
	echo "bad luck"
elif [ $i -eq 3 ]; then
	echo "good luck"
else
	echo "Best School"
fi
((i++))
done
