#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely. Sleeps between loops

hate () {
	echo "I hate the kill command";
	rm /var/run/myscript.pid;
	pkill -9 -f ".10-process_and_pid_file"
	exit
}
love () {
	echo "Y U no love me?!";
	pkill -15 -f ".10-process_and_pid_file"
}
quit () {
	rm /var/run/myscript.pid;
	pkill -1 -f ".10-process_and_pid_file"
}

trap hate SIGTERM
trap love SIGINT
trap quit SIGQUIT

pgrep -a bash | grep "10-process_and_pid_file" | awk '{print $1}' > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2
done
