#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely. Sleeps between loops

exit () {
	echo "I hate the kill command"
}

love () {
	echo "Y U no love me?!"
}

trap exit SIGTERM
trap love SIGINT

echo $(pgrep -a bash | grep "10-process_and_pid_file" | awk '{print $1}') > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2
done
