#!/usr/bin/env bash
# Manage processes
startit () {
		./manage_my_process &
		pgrep -a bash | grep "manage_my_process" | awk '{print $1}' > /var/run/my_process.pid
		echo "manage_my_process started"
	}
stopit () {
		pkill -f "./manage_my_process"
		echo "manage_my_process stopped"
		rm /var/run/my_process.pid
	}
restartit () {
		pkill -f "./manage_my_process"
		./manage_my_process &
		pgrep -a bash | grep "manage_my_process" | awk '{print $1}' > /var/run/my_process.pid
		echo "manage_my_process restarted"
                rm /var/run/my_process.pid
	}

case "$1" in
	start ) startit ;;
	stop ) stopit ;;
	restart ) restartit;;
	* ) echo "Usage: manage_my_process {start|stop|restart}" ;;
esac
rm /var/run/my_process.pid
