#!/usr/bin/env bash
# Script that displays To infinity and beyond indefinitely. Sleeps between loops

case "$1" in
	start ) 
		./manage_my_process &
		pgrep -a bash | grep "manage_my_process" | awk '{print $1}' > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop )
		echo $(sudo rm -f /var/run/my_process.pid);
		pkill -f "./manage_my_process"
		echo "manage_my_process stopped"
		;;
	restart )
		echo $(sudo rm -f /var/run/my_process.pid);
		pkill -f "./manage_my_process"
		./manage_my_process &
		pgrep -a bash | grep "manage_my_process" | awk '{print $1}' > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	* )
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
